apiVersion: apps/v1
kind: Deployment
metadata:
  name: limoneno-backend
spec:
  template:
    spec:
      containers:
      - name: limoneno-backend
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        env:
        - name: RAILS_ENV
          value: production
        - name: RAILS_MAX_THREADS
          value: "5"
        - name: DATABASE_HOST
          value: mysql
        - name: DATABASE_PORT
          value: "3306"
        - name: DATABASE_NAME
          value: limoneno
        - name: DATABASE_NAME
          value: limoneno
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: limoneno-backend-db-staging
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: limoneno-backend-db-staging
              key: password
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: limoneno-backend-secret-key-base-staging
              key: secret

        - name: REDIS_URL
          value: redis://redis-staging
