apiVersion: apps/v1
kind: Deployment
metadata:
  name: limoneno-backend
spec:
  template:
    spec:
      containers:
      - name: limoneno-backend
        image: 953994510734.dkr.ecr.us-east-1.amazonaws.com/limoneno-backend
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP

        startupProbe:
          httpGet:
            path: /api/v1
            port: 5000
            scheme: HTTP
          failureThreshold: 10
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /api/v1
            port: 5000
            scheme: HTTP
          failureThreshold: 10
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /api/v1
            port: 5000
            scheme: HTTP
          failureThreshold: 10
          periodSeconds: 10