name: Limoneno backend workflow

on:
    push:
        branches: [master]
    workflow_dispatch:

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: us-east-1
    CLUSTER_NAME: limoneno

jobs:
    build:
        name: Build image
        runs-on: ubuntu-latest
        steps:
        - name: Check out repository
          uses: actions/checkout@v2

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ env.AWS_DEFAULT_REGION }}

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1

        - name: Install skaffold
          run: |
            curl -L -o /tmp/skaffold https://storage.googleapis.com/skaffold/releases/v1.32.0/skaffold-linux-amd64
            sudo install /tmp/skaffold /usr/local/bin/

        - name: Build Image
          run: |
            skaffold build -p prod --file-output build-state.json

        - name: Upload build state
          uses: actions/upload-artifact@v2
          with:
            name: build-state
            path: build-state.json

    tests:
      name: Tests
      runs-on: ubuntu-latest
      env:
        RAILS_ENV: test
        DATABASE_HOST: "127.0.0.1"
        DATABASE_PORT: "3306"
        DATABASE_NAME: limoneno
        DATABASE_USERNAME: limoneno_test
        DATABASE_PASSWORD: limoneno_test
        REDIS_URL: redis://127.0.0.1
        AWS_BUCKET: fernando-limoneno-backend-test

      services:
        mysql:
          image: mysql:5.7.35
          env:
            MYSQL_USER: ${{ env.DATABASE_USERNAME }}
            MYSQL_DATABASE: ${{ env.DATABASE_NAME }}_test
            MYSQL_PASSWORD: ${{ env.DATABASE_PASSWORD }}
            MYSQL_ROOT_PASSWORD: ${{ env.DATABASE_PASSWORD }}
          ports:
          - 3306:3306
          options: >-
            --health-cmd="mysqladmin ping"
            --health-interval=10s
            --health-timeout=5s
            --health-retries=10
        redis:
          image: redis
          options: >-
            --health-cmd "redis-cli ping"
            --health-interval=10s
            --health-timeout=5s
            --health-retries=10
          ports:
          - 6379:6379

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Setup Ruby and install gems
          uses: ruby/setup-ruby@v1
          with:
            bundler-cache: true

        - name: Setup test database
          run: |
            bin/rails db:setup

        - name: Run tests
          run: bin/rails test

    deploy:
        name: Deploy to cluster
        needs: [build, tests]
        runs-on: ubuntu-latest
        steps:
        - name: Check out repository
          uses: actions/checkout@v2

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ env.AWS_DEFAULT_REGION }}

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1

        - name: Create kubeconfig
          run: |
            aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }}

        - name: Install kustomize, kubectl and skaffold
          run: |
            cd /tmp
            curl -L -o /tmp/kubectl "https://storage.googleapis.com/kubernetes-release/release/v1.22.2/bin/linux/amd64/kubectl"
            sudo install /tmp/kubectl /usr/local/bin/
            curl -L -o /tmp/skaffold https://storage.googleapis.com/skaffold/releases/v1.32.0/skaffold-linux-amd64
            sudo install /tmp/skaffold /usr/local/bin/
            curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash

        - name: Download build state
          uses: actions/download-artifact@v2
          with:
            name: build-state

        - name: Deploy to cluster
          run: |
            skaffold deploy -n limoneno -p prod -a build-state.json -n limoneno
